# Generated by Django 5.0.4 on 2024-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docatapp', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='petimage',
            field=models.ImageField(default='x', upload_to='images/'),
        ),
    ]
