# Generated by Django 5.0.4 on 2024-06-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docatapp', '0007_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
