# Generated by Django 5.0.4 on 2024-06-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docatapp', '0008_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
